'use client';

import Link from 'next/link';
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCartStore, getCartSubtotal, getCartSavings } from '@/store/cart-store';
import { formatINR } from '@/lib/format';

export default function CartPage() {
  const { items, updateQuantity, removeItem } = useCartStore();
  const subtotal = getCartSubtotal(items);
  return <div className="container-ardenby py-12"><h1 className="font-display text-4xl font-bold">Your cart</h1>{items.length === 0 ? <div className="text-center py-24"><ShoppingBag className="h-12 w-12 mx-auto text-muted-foreground" /><p className="mt-4 text-muted-foreground">Your cart is waiting for something good.</p><Link href="/shop" className="inline-block mt-6 rounded-xl bg-ink text-cream px-6 py-3 font-semibold">Continue shopping</Link></div> : <div className="grid lg:grid-cols-[1fr_360px] gap-10 mt-10"><div className="space-y-4">{items.map((item) => <div key={`${item.productId}-${item.size}-${item.color}`} className="flex gap-4 border-b border-border pb-5"><img src={item.image} alt={item.name} className="w-24 h-28 rounded-xl object-cover" /><div className="flex-1"><Link href={`/product/${item.slug}`} className="font-semibold hover:text-olive">{item.name}</Link><p className="text-sm text-muted-foreground mt-1">Size {item.size} · {item.color}</p><p className="font-bold mt-2">{formatINR(item.price)}</p><div className="flex items-center gap-3 mt-3"><button aria-label="Decrease quantity" onClick={() => updateQuantity(item.productId, item.size, item.color, item.quantity - 1)}><Minus className="h-4 w-4" /></button><span>{item.quantity}</span><button aria-label="Increase quantity" onClick={() => updateQuantity(item.productId, item.size, item.color, item.quantity + 1)}><Plus className="h-4 w-4" /></button></div></div><button aria-label={`Remove ${item.name}`} onClick={() => removeItem(item.productId, item.size, item.color)}><Trash2 className="h-4 w-4 text-destructive" /></button></div>)}</div><aside className="rounded-2xl bg-muted p-6 h-fit"><h2 className="font-display text-2xl font-bold">Summary</h2><div className="flex justify-between mt-6"><span>Subtotal</span><strong>{formatINR(subtotal)}</strong></div><div className="flex justify-between mt-3 text-olive"><span>You save</span><span>{formatINR(getCartSavings(items))}</span></div><div className="border-t border-border mt-5 pt-5 flex justify-between text-lg"><strong>Total</strong><strong>{formatINR(subtotal)}</strong></div><Link href="/checkout" className="block text-center rounded-xl bg-ink text-cream py-4 mt-6 font-semibold">Checkout</Link></aside></div>}</div>;
}
